kind: Pod
apiVersion: v1
metadata:
  name: annotations
  labels:
    course: k8
    trainer: sivakumar
  annotations:
    kubernets.io/created-ny: 'sivakumar'
    jenkins.build.url: 'https://jenkins.rlsu.shop/expense/job/backend/54'
spec:
  containers:
  - name: nginx
    image: nginx