
kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
       memory: "128mi"
       cpu: "100m"
    limits:
       memory: "128Mi"
       cpu: "500m"