apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 1
       preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - expense
  - name: with-node-affinity
    image: nginx 