
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic
  resources:
    requests:
      storage: 5Gi
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: efs-app
# spec:
#   containers:
#     - name: app
#       image: centos
#       command: ["/bin/sh"]
#       args: ["-c", "while true; do echo $(date -u) >> /data/out; sleep 5; done"]
#       volumeMounts:
#         - name: persistent-storage
#           mountPath: /data
#   volumes:
#     - name: persistent-storage
#       persistentVolumeClaim:
#         claimName: efs-claim
